kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poduser
  namespace: default
subjects:
- kind: User
  name: jagad # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: user-role 
  apiGroup: rbac.authorization.k8s.io
